is_dnn: false

data:
  root: "./datasets/"
  dataset: "RAW"
  sequence: "room"
  height: 360
  width: 640
  load_gt_flow: False
  load_timestamp: False
  n_events_per_batch: 30000
  ind1: 0
  ind2: 100000

output:
  output_dir: "./outputs/myraw_room/"
  show_interactive_result: false

solver:
  method: "pyramidal_patch_contrast_maximization"
  time_aware: False
  patch:
    initialize: "random"
    scale: 5
    crop_height: 352
    crop_width: 640
    filter_type: "bilinear"
  motion_model: "2d-translation"
  warp_direction: "first"
  parameters:
    - "trans_x"
    - "trans_y"
  cost: "hybrid"
  outer_padding: 0
  cost_with_weight:
    multi_focal_normalized_gradient_magnitude: 1.
    total_variation: 0.01
  iwe:
    method: "bilinear_vote"
    blur_sigma: 1
  calib: False

optimizer:
  n_iter: 40
  method: "Newton-CG"
  max_iter: 50
  parameters:
    trans_x:
      min: -150
      max: 150
    trans_y:
      min: -150
      max: 150
